"""Create Purchase table

Revision ID: 6376edf9842f
Revises: 
Create Date: 2025-04-05 10:40:00.436542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6376edf9842f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('product_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.alter_column('product_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('purchase_date')

    # ### end Alembic commands ###
